version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - save_cache:
          key: dist-{{ epoch }}
          paths:
            - ~/repo/dist
  deploy:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dist-
      - run: |
          git config --global user.name 'Masaya Takeda'
          git config --global user.email '844196@gmail.com'
          rm .gitignore
          git add dist
          git commit --message '[CI SKIP] update'
          git subtree split --branch gh-pages --prefix dist
          git push --force origin gh-pages:gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
